# Taken from https://github.com/joey711/phyloseq

language: r
bioc_required: true
warnings_are_errors: false
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com
   - _R_CHECK_DONTTEST_EXAMPLES_=FALSE

notifications:
  email:
    on_success: change
    on_failure: change
